"""Added new column father name and removed no_of_shares

Revision ID: 2f3666da405b
Revises: c6ddde54c10f
Create Date: 2026-06-27 16:30:09.973415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3666da405b'
down_revision: Union[str, Sequence[str], None] = 'c6ddde54c10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('father_name', sa.String(), nullable=True))
    op.drop_column('shares', 'no_of_shares')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('no_of_shares', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('shares', 'father_name')
    # ### end Alembic commands ###
