"""Added micr_no

Revision ID: 3a323927f5a5
Revises: e9ba02b6b6c5
Create Date: 2026-07-01 02:04:28.496507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a323927f5a5'
down_revision: Union[str, Sequence[str], None] = 'e9ba02b6b6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('micr_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shares', 'micr_no')
    # ### end Alembic commands ###
