"""create shares table

Revision ID: 6c1fef847762
Revises: 
Create Date: 2026-06-26 18:52:58.805275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1fef847762'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folio_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('pin_code', sa.Integer(), nullable=True),
    sa.Column('number_of_shares', sa.Integer(), nullable=True),
    sa.Column('net_dividend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('war_no', sa.Integer(), nullable=True),
    sa.Column('chq_no', sa.Integer(), nullable=True),
    sa.Column('no_of_shares', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shares')
    # ### end Alembic commands ###
