"""Added demat_acc_no

Revision ID: 75a2e99f1534
Revises: 3a323927f5a5
Create Date: 2026-07-08 16:31:21.003780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a2e99f1534'
down_revision: Union[str, Sequence[str], None] = '3a323927f5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('demat_acc_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shares', 'demat_acc_no')
    # ### end Alembic commands ###
