"""added pan_no, aadhar_no, date_of_birth, joint_holder_name

Revision ID: bd7d7b6671f0
Revises: 75a2e99f1534
Create Date: 2026-07-11 23:45:05.831733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7d7b6671f0'
down_revision: Union[str, Sequence[str], None] = '75a2e99f1534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('pan_no', sa.String(), nullable=True))
    op.add_column('shares', sa.Column('aadhar_no', sa.String(), nullable=True))
    op.add_column('shares', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('shares', sa.Column('joint_holder_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shares', 'joint_holder_name')
    op.drop_column('shares', 'date_of_birth')
    op.drop_column('shares', 'aadhar_no')
    op.drop_column('shares', 'pan_no')
    # ### end Alembic commands ###
