"""Added company column to shares table

Revision ID: be7d3b56816d
Revises: 6c1fef847762
Create Date: 2026-06-26 19:17:56.847548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7d3b56816d'
down_revision: Union[str, Sequence[str], None] = '6c1fef847762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shares', 'company')
    # ### end Alembic commands ###
