"""Add date_of_transfer column

Revision ID: d96ed0c10b6f
Revises: 2f3666da405b
Create Date: 2026-06-29 19:20:01.313325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96ed0c10b6f'
down_revision: Union[str, Sequence[str], None] = '2f3666da405b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('date_of_transfer', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shares', 'date_of_transfer')
    # ### end Alembic commands ###
