"""add dp_id

Revision ID: e9ba02b6b6c5
Revises: d96ed0c10b6f
Create Date: 2026-06-30 18:35:09.965469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ba02b6b6c5'
down_revision: Union[str, Sequence[str], None] = 'd96ed0c10b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('dp_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shares', 'dp_id')
    # ### end Alembic commands ###
